export const FETCH_USER = "FETCH_USER";
export const FETCH_CONVERSATION_WITH = "FETCH_CONVERSATION_WITH";
export const ADD_LOCAL_MSG_TO_CONVERSATION = 'ADD_LOCAL_MSG_TO_CONVERSATION';
export const SET_MESSAGE = "SET_MESSAGE";
export const SEND_MESSAGE_TO = "SEND_MESSAGE_TO";
